### ISSUE TITLE
Suggestion to use main instead of master

### ISSUE THREAD

**Issue by riverma** [unity-sds/unity-sds.github.io#7]
## Brief Description
All other Unity repos use the `main` branch name as opposed to `master`. It would be more consistent if we did the same for this repo.

Also please see: https://www.theserverside.com/feature/Why-GitHub-renamed-its-master-branch-to-main

## Expected Behavior
Suggestion to use `main` instead of `master`

## Current Behavior
`master` branch is the default branch

**Comment by riverma** [comment]
FYI @mike-gangl - this will help with consistency among other Unity repos as well. Thanks!

**Comment by mike-gangl** [comment]
Closing as we are archiving this.
